[package]
name = "extrablatt"
version = "0.1.0"
authors = ["Matthias Seitz <matthias.seitz@tum.de>"]
edition = "2018"
repository = "https://github.com/mattsse/extrablatt"
categories = ["parsing"]
keywords = ["parser", "web", "news"]
description= "News, articles and text scraper"
documentation = "https://docs.rs/extrablatt/"

[badges]
travis-ci = { repository = "mattsse/extrablatt", branch = "master" }

[dependencies]
structopt = { version = "0.2", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
select = { git = "https://github.com/utkarshkukreti/select.rs" }
anyhow = "1.0"
log = "0.4"
tokio = "=0.2.0-alpha.6"
thiserror = "1.0"
reqwest = "=0.10.0-alpha.2"
archiveis = { version = "0.3", optional = true }
regex = "1.3"
rss = "1.8"
lazy_static = "1.4"
chrono = "0.4"
dtparse = "1.0"
wasm-timer = "0.2"
lru = "0.4"
fnv = "1.0"
url = "2.1"
bytes = "0.4"
pretty_env_logger = "0.3"
futures = "0.3"

[features]
cli = ["structopt"]
archive = ["archiveis"]
serde0 = ["serde", "serde_json"]


[dev-dependencies]
tempdir = "0.3"
